Repository PopPool/iOS, pull requests merged in 2025-05, with the labels that each got.

#133 [FIX] 스크롤이 튕기는 문제 해결
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Search/BeforeSearch/SearchController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Search/BeforeSearch/SearchReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Search/BeforeSearch/View/SearchView.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Search/Main/SearchMainController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Search/Main/SearchMainView.swift
Labels: 🔄 refactor, 🐛 fix

#128 [FEAT] #127 OSLog도입
  Poppool/CoreLayer/Infrastructure/Infrastructure.xcodeproj/project.pbxproj
  Poppool/CoreLayer/Infrastructure/Infrastructure/Logger/Logger.swift
  Poppool/CoreLayer/Infrastructure/Infrastructure/Service/KeyChainService.swift
  Poppool/DataLayer/Data/Data/Network/API/PreSignedAPI/PreSignedAPIEndPoint.swift
  Poppool/DataLayer/Data/Data/Network/Common/Requestable.swift
  Poppool/DataLayer/Data/Data/Network/EndPoint/MultipartEndPoint.swift
  Poppool/DataLayer/Data/Data/Network/Interceptor/TokenInterceptor.swift
  Poppool/DataLayer/Data/Data/Network/Provider/ProviderImpl.swift
  Poppool/DataLayer/Data/Data/Network/Service/AppleLoginService.swift
  Poppool/DataLayer/Data/Data/Network/Service/KakaoLoginService.swift
  Poppool/DataLayer/Data/Data/Network/Service/PreSignedService.swift
  Poppool/DataLayer/Data/Data/RepositoryImpl/MapRepositoryImpl.swift
  Poppool/DomainLayer/Domain/Domain/UseCaseImpl/AdminUseCaseImpl.swift
  Poppool/DomainLayer/Domain/Domain/UseCaseImpl/MapUseCaseImpl.swift
  Poppool/Poppool.xcodeproj/project.pbxproj
  Poppool/Poppool.xcodeproj/xcshareddata/xcschemes/Poppool.xcscheme
  Poppool/Poppool/Resource/Assets.xcassets/Marker/Marker.imageset/Contents.json
  Poppool/Poppool/Resource/Assets.xcassets/Marker/Marker.imageset/solid.png
  Poppool/Poppool/Resource/Assets.xcassets/Marker/Marker.imageset/solid.svg
  Poppool/Poppool/Resource/Assets.xcassets/Marker/TapMarker.imageset/Contents.json
  Poppool/Poppool/Resource/Assets.xcassets/Marker/TapMarker.imageset/solid.png
  Poppool/Poppool/Resource/Assets.xcassets/Marker/TapMarker.imageset/solid.svg
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminBottomSheet/AdminBottomSheetView.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminBottomSheet/AdminBottomSheetViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminRegister/PopUpStoreRegisterReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminStoreCell.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Comment/CommentDetail/CommentDetailReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Comment/CommentList/CommentListReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Comment/NormalCommentAdd/NormalCommentAddReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Comment/NormalCommentEdit/NormalCommentEditReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Detail/DetailReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/BalloonBackgroundView.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/BalloonChipCell.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/FilterChip.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FindMap/MapGuideView/FullScreenMapViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FindMap/MapGuideView/MapGuideReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/MapView/MapMarker.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/MapView/MapReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/MapView/MapViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/StoreListView/StoreListReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/MyPage/ProfileEdit/Main/ProfileEditController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Utills/Common/ClusteringManager.swift
  Poppool/PresentationLayer/Presentation/Presentation/Utills/Controllers/BaseTabmanController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Utills/Controllers/BaseViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Utills/Interfaces/Sectionable/SectionSupplementaryItem.swift
  Poppool/PresentationLayer/Presentation/Presentation/Utills/Interfaces/Sectionable/Sectionable.swift
Labels: 🚀 feat

#136 [FIX] 이미지 블링크 문제 개선
  Poppool/CoreLayer/Infrastructure/Infrastructure/Extension/UIImageView+.swift
Labels: 🐛 fix

#137 [FIX] 서브지역 카테고리 라벨 상단이 짤리던 이슈 수정
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/BalloonBackgroundView.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/BalloonChipCell.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FillterSheetView/FilterBottomSheetView.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/MapView/MapViewController.swift
Labels: 🐛 fix

#148 풀스크린맵뷰 애니메이션 제거와 어드민페이지 수정화면 정상화
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Admin/AdminViewController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Map/FindMap/MapGuideView/FullScreenMapViewController.swift
Labels: 🔄 refactor, 🐛 fix

#151 [REFACTOR] 레이아웃 팩토리 개선 및 빌더 도입
  .coderabbit.yaml
  .gitignore
  Poppool/CoreLayer/Infrastructure/Infrastructure/Extension/Collection+.swift
  Poppool/PresentationLayer/DesignSystem/DesignSystem/Components/Layout/CollectionLayoutBuilder.swift
  Poppool/PresentationLayer/DesignSystem/DesignSystem/Components/Layout/CollectionLayoutProvidable.swift
  Poppool/PresentationLayer/DesignSystem/DesignSystem/Components/Layout/GridCollectionLayoutProvider.swift
  Poppool/PresentationLayer/DesignSystem/DesignSystem/Components/Layout/HeaderLayoutProvidable.swift
  Poppool/PresentationLayer/DesignSystem/DesignSystem/Components/Layout/TagCollectionLayoutProvider.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature.xcodeproj/project.pbxproj
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/Factory/PopupSearchLayoutFactory.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/Reactor/PopupSearchReactor.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/SectionType/Section.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/View/Component/Cell/SearchResultEmptyCollectionViewCell.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/View/PopupSearchView.swift
  Poppool/PresentationLayer/SearchFeature/SearchFeature/PopupSearch/View/PopupSearchViewController.swift
Labels: 🔄 refactor, 🚀 feat
