Repository PopPool/iOS, pull requests merged in 2025-04, with the labels that each got.

#95 카테고리 시트뷰 터치영역 이슈
  Poppool/Poppool.xcodeproj/project.pbxproj
  Poppool/Poppool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Poppool/Poppool/Application/AppDelegate.swift
  Poppool/Poppool/Presentation/Admin/AdminRegister/PopUpStoreRegisterViewController.swift
  Poppool/Poppool/Presentation/Admin/AdminViewController.swift
  Poppool/Poppool/Presentation/Admin/Data/MapDomain/MapPopUpStore.swift
  Poppool/Poppool/Presentation/Admin/Data/MapDomain/MapPopUpStoreDTO.swift
  Poppool/Poppool/Presentation/Admin/Data/MapDomain/Repository/MapRepository.swift
  Poppool/Poppool/Presentation/Map/Common/ClusteringManager.swift
  Poppool/Poppool/Presentation/Map/Common/ClusteringModels.swift
  Poppool/Poppool/Presentation/Map/Common/GMSMapViewDelegateProxy.swift
  Poppool/Poppool/Presentation/Map/Common/MapUtilities.swift
  Poppool/Poppool/Presentation/Map/Common/NMFMapViewDelegateProxy.swift
  Poppool/Poppool/Presentation/Map/Common/RegionDefinitions.swift
  Poppool/Poppool/Presentation/Map/FillterSheetView/BalloonBackgroundView.swift
  Poppool/Poppool/Presentation/Map/FillterSheetView/BalloonChipCell.swift
  Poppool/Poppool/Presentation/Map/FillterSheetView/FilterBottomSheetView.swift
  Poppool/Poppool/Presentation/Map/FillterSheetView/FilterBottomSheetViewController.swift
  Poppool/Poppool/Presentation/Map/FillterSheetView/FilterChipsView.swift
  Poppool/Poppool/Presentation/Map/FindMap/MapGuideView/FullScreenMapViewController.swift
  Poppool/Poppool/Presentation/Map/FindMap/MapGuideView/MapGuideAppService.swift
  Poppool/Poppool/Presentation/Map/FindMap/MapGuideView/MapGuideViewController.swift
  Poppool/Poppool/Presentation/Map/MapView/MapMarker.swift
  Poppool/Poppool/Presentation/Map/MapView/MapReactor.swift
  Poppool/Poppool/Presentation/Map/MapView/MapView.swift
  Poppool/Poppool/Presentation/Map/MapView/MapViewController.swift
  Poppool/Poppool/Presentation/Map/StoreListView/StoreListReactor.swift
  Poppool/Poppool/Presentation/Map/StoreListView/StoreListViewController.swift
Labels: 🔄 refactor, 🐛 fix

#100 [FIX] 사진이 한장일 때 무한 스크롤을 방지하도록 수정
  Poppool/Poppool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Poppool/Poppool/Presentation/Scene/Detail/DetailController.swift
  Poppool/Poppool/Presentation/Scene/Home/Main/HomeController.swift
  Poppool/Poppool/Presentation/Scene/Home/Main/HomeReactor.swift
  Poppool/Poppool/Presentation/Scene/Home/Main/View/ImageBannerSection/ImageBannerSection/ImageBannerSectionCell.swift
Labels: 🎨 style, 🐛 fix

#97 [REFACTOR] Kingfisher 기능을 대체하기 위한 ImageLoader 개발
  Poppool/Poppool.xcodeproj/project.pbxproj
  Poppool/Poppool.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Poppool/Poppool/Infrastructure/ImageLoader/DiskStorage.swift
  Poppool/Poppool/Infrastructure/ImageLoader/ImageLoader.swift
  Poppool/Poppool/Infrastructure/ImageLoader/MemoryStorage.swift
  Poppool/Poppool/Presentation/Extension/String?+.swift
  Poppool/Poppool/Presentation/Extension/UIImageView+.swift
  Poppool/Poppool/Presentation/Map/Common/MapPopupCardView/PopupCardCell.swift
  Poppool/Poppool/Presentation/Scene/Detail/DetailController.swift
  Poppool/Poppool/Presentation/Scene/Home/Main/View/HomeCardSection/HomeCardSectionCell.swift
  Poppool/Poppool/Presentation/Scene/Home/Main/View/HomePopularCardSection/HomePopularCardSectionCell.swift
Labels: 🔄 refactor

#106 PopUpRegisterViewControler 분리
  Poppool/Poppool.xcodeproj/project.pbxproj
  Poppool/Poppool/Presentation/Admin/AdminRegister/PopUpImagesCollectionView.swift
  Poppool/Poppool/Presentation/Admin/AdminRegister/PopUpStoreRegisterReactor.swift
  Poppool/Poppool/Presentation/Admin/AdminRegister/PopUpStoreRegisterView.swift
  Poppool/Poppool/Presentation/Admin/AdminRegister/PopUpStoreRegisterViewController.swift
  Poppool/Poppool/Presentation/Admin/Common/DateTimePickerManager.swift
Labels: 🔄 refactor

#115 [REFACTOR] DIContainer 구현 및 Presentation layer에 외부 의존성 제거
  Poppool/Poppool/Application/AppDelegate.swift
  Poppool/Poppool/CoreLayer/Infrastructure/DIContainer/DIContainer.swift
  Poppool/Poppool/CoreLayer/Infrastructure/DIContainer/DependencyWrapper.swift
  Poppool/Poppool/CoreLayer/Infrastructure/Service/PreSignedService.swift
  Poppool/Poppool/DataLayer/Network/Interceptor/TokenInterceptor.swift
  Poppool/Poppool/DataLayer/Network/Provider/ProviderImpl.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminRegister/PopUpStoreRegisterReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminRegister/PopUpStoreRegisterViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/CommentDetail/CommentDetailReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/CommentList/CommentListReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/NormalCommentAdd/NormalCommentAddReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/NormalCommentEdit/NormalCommentEditReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/OtherUserComment/OtherUserCommentReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Detail/DetailReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Home/List/HomeListReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Home/Main/HomeReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Login/Main/LoginReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Login/Sub/SubLoginReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/FindMap/MapGuideView/MapGuideReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/FindMap/MapGuideView/MapGuideViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/MapView/MapReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/MapView/MapViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/StoreListView/StoreListReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/StoreListView/StoreListViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Block/BlockUserManageReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Bookmark/Main/MyPageBookmarkReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Main/MyPageReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/MyComment/Main/MyCommentReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Notice/Detail/MyPageNoticeDetailReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Notice/List/MyPageNoticeReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/ProfileEdit/CategoryEditModal/CategoryEditModalReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/ProfileEdit/InfoEditModal/InfoEditModalReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/ProfileEdit/Main/ProfileEditReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Recent/MyPageRecentReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Withdrawl/SelectedReason/WithdrawlReasonReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Search/AfterSearch/SearchResultReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Search/BeforeSearch/SearchReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Search/CategoryController/SearchCategoryReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Search/Main/SearchMainController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/SignUp/Main/SignUpMainController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/SignUp/Main/SignUpMainReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/SignUp/Step2/SignUpStep2Reactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/SignUp/Step3/SignUpStep3Reactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Splash/SplashController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/TabbarController/TabbarController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Utills/ToastMaker/ToastMaker.swift
Labels: 🔄 refactor, 🚀 feat

#117 [REFACTOR] Domain Layer에서 DTO 제거
  Poppool/Poppool/DataLayer/Network/API/HomeAPI/HomeAPIEndpoint.swift
  Poppool/Poppool/DataLayer/Network/API/HomeAPI/RequestDTO/HomeSortedRequestDTO.swift
  Poppool/Poppool/DataLayer/Network/API/SortedRequestDTO.swift
  Poppool/Poppool/DataLayer/Network/API/UserAPI/RequesetDTO/GetBlockUserListRequestDTO.swift
  Poppool/Poppool/DataLayer/Network/API/UserAPI/RequesetDTO/UserSortedRequestDTO.swift
  Poppool/Poppool/DataLayer/Network/API/UserAPI/UserAPIEndPoint.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/HomeAPIRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/PopUpAPIRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/UserAPIRepositoryImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/HomeAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/PopUpAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/SignUpAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/UserAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/HomeAPIRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/PopUpAPIRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/UserAPIRepository.swift
Labels: 🔄 refactor

#120 REAFACTOR: Domain Layer DTO 제거
  Poppool/Poppool/DataLayer/Network/API/AdminAPI/AdminAPIEndpoint.swift
  Poppool/Poppool/DataLayer/Network/API/AdminAPI/ResponseDTO/AdminResponseDTO.swift
  Poppool/Poppool/DataLayer/Network/API/MapAPI/MapAPIEndpoint.swift
  Poppool/Poppool/DataLayer/Network/API/MapAPI/ResponseDTO/MapPopUpStoreDTO.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/AdminRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/AuthAPIRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/CommentAPIRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/MapDirectionRepositoryImpl.swift
  Poppool/Poppool/DataLayer/RepositoryImpl/MapRepositoryImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/AdminUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/AuthAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/CommentAPIUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/Domain/UseCaseImpl/MapUseCaseImpl.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Entity/AdminResponse/AdminStore.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Entity/AdminResponse/AdminStoreDetail.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Entity/AdminResponse/Params/AdminParams.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Entity/MapResponse/MapPopUpStore.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/AdminRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/AuthAPIRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/CommentAPIRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/Repository/MapRepository.swift
  Poppool/Poppool/DomainLayer/DomainInterface/UseCase/AdminUseCase.swift
  Poppool/Poppool/DomainLayer/DomainInterface/UseCase/CommentAPIUseCase.swift
  Poppool/Poppool/DomainLayer/DomainInterface/UseCase/MapUseCase.swift
  Poppool/Poppool/DomainLayer/DomainInterface/UseCase/SignUpAPIUseCase.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminRegister/PopUpStoreRegisterReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminRegister/PopUpStoreRegisterViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminStoreCell.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Admin/AdminViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Comment/NormalCommentEdit/NormalCommentEditReactor.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/Map/MapView/MapViewController.swift
  Poppool/Poppool/PresentationLayer/Presentation/Scene/MyPage/Main/MyPageReactor.swift
Labels: 🔄 refactor

#125 [FIX] 카카오 로그인이 동작하지 않던 문제 수정
  Poppool/DataLayer/Data/Data.xcodeproj/project.pbxproj
  Poppool/DataLayer/Data/Data/Network/Service/AppleLoginService.swift
  Poppool/DataLayer/Data/Data/Network/Service/AuthServiceable.swift
  Poppool/DataLayer/Data/Data/Network/Service/KakaoLoginService.swift
  Poppool/DataLayer/Data/Data/RepositoryImpl/AppleLoginRepositoryImpl.swift
  Poppool/DataLayer/Data/Data/RepositoryImpl/KakaoLoginRepositoryImpl.swift
  Poppool/DomainLayer/Domain/Domain/UseCaseImpl/AppleLoginUseCaseImpl.swift
  Poppool/DomainLayer/Domain/Domain/UseCaseImpl/KakaoLoginUseCaseImpl.swift
  Poppool/DomainLayer/Domain/DomainInterface/Repository/AppleLoginRepository.swift
  Poppool/DomainLayer/Domain/DomainInterface/Repository/KakaoLoginRepository.swift
  Poppool/DomainLayer/Domain/DomainInterface/UseCase/AppleLoginUseCase.swift
  Poppool/DomainLayer/Domain/DomainInterface/UseCase/KakaoLoginUseCase.swift
  Poppool/Poppool.xcodeproj/project.pbxproj
  Poppool/Poppool.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Poppool/Poppool/Application/AppDelegate.swift
  Poppool/PresentationLayer/Presentation/Presentation.xcodeproj/project.pbxproj
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Detail/DetailReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Login/Main/LoginController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Login/Main/LoginReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Login/Sub/SubLoginController.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Login/Sub/SubLoginReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/MyPage/Main/MyPageReactor.swift
  Poppool/PresentationLayer/Presentation/Presentation/Scene/Splash/SplashController.swift
Labels: 🔄 refactor, 🐛 fix, 🔧 chore
